// <auto-generated>
/*
 * BaSyx AAS Environment Component
 *
 * AAS Environment API
 *
 * The version of the OpenAPI document: 2.0
 * Contact: basyx-dev@eclipse.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using MnestixSearcher.Clients.Client;

namespace MnestixSearcher.Clients.Model
{
    /// <summary>
    /// AnnotatedRelationshipElement
    /// </summary>
    public partial class AnnotatedRelationshipElement : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AnnotatedRelationshipElement" /> class.
        /// </summary>
        /// <param name="embeddedDataSpecifications">embeddedDataSpecifications</param>
        /// <param name="displayName">displayName</param>
        /// <param name="description">description</param>
        /// <param name="category">category</param>
        /// <param name="idShort">idShort</param>
        /// <param name="extensions">extensions</param>
        /// <param name="semanticId">semanticId</param>
        /// <param name="supplementalSemanticIds">supplementalSemanticIds</param>
        /// <param name="qualifiers">qualifiers</param>
        /// <param name="first">first</param>
        /// <param name="second">second</param>
        /// <param name="annotations">annotations</param>
        [JsonConstructor]
        public AnnotatedRelationshipElement(Option<List<EmbeddedDataSpecification>?> embeddedDataSpecifications = default, Option<List<LangStringNameType>?> displayName = default, Option<List<LangStringTextType>?> description = default, Option<string?> category = default, Option<string?> idShort = default, Option<List<Extension>?> extensions = default, Option<Reference?> semanticId = default, Option<List<Reference>?> supplementalSemanticIds = default, Option<List<Qualifier>?> qualifiers = default, Option<Reference?> first = default, Option<Reference?> second = default, Option<List<AnnotatedRelationshipElementAllOfAnnotations>?> annotations = default)
        {
            EmbeddedDataSpecificationsOption = embeddedDataSpecifications;
            DisplayNameOption = displayName;
            DescriptionOption = description;
            CategoryOption = category;
            IdShortOption = idShort;
            ExtensionsOption = extensions;
            SemanticIdOption = semanticId;
            SupplementalSemanticIdsOption = supplementalSemanticIds;
            QualifiersOption = qualifiers;
            FirstOption = first;
            SecondOption = second;
            AnnotationsOption = annotations;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of EmbeddedDataSpecifications
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<EmbeddedDataSpecification>?> EmbeddedDataSpecificationsOption { get; private set; }

        /// <summary>
        /// Gets or Sets EmbeddedDataSpecifications
        /// </summary>
        [JsonPropertyName("embeddedDataSpecifications")]
        public List<EmbeddedDataSpecification>? EmbeddedDataSpecifications { get { return this.EmbeddedDataSpecificationsOption; } set { this.EmbeddedDataSpecificationsOption = new(value); } }

        /// <summary>
        /// Used to track the state of DisplayName
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<LangStringNameType>?> DisplayNameOption { get; private set; }

        /// <summary>
        /// Gets or Sets DisplayName
        /// </summary>
        [JsonPropertyName("displayName")]
        public List<LangStringNameType>? DisplayName { get { return this.DisplayNameOption; } set { this.DisplayNameOption = new(value); } }

        /// <summary>
        /// Used to track the state of Description
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<LangStringTextType>?> DescriptionOption { get; private set; }

        /// <summary>
        /// Gets or Sets Description
        /// </summary>
        [JsonPropertyName("description")]
        public List<LangStringTextType>? Description { get { return this.DescriptionOption; } set { this.DescriptionOption = new(value); } }

        /// <summary>
        /// Used to track the state of Category
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> CategoryOption { get; private set; }

        /// <summary>
        /// Gets or Sets Category
        /// </summary>
        [JsonPropertyName("category")]
        public string? Category { get { return this.CategoryOption; } set { this.CategoryOption = new(value); } }

        /// <summary>
        /// Used to track the state of IdShort
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> IdShortOption { get; private set; }

        /// <summary>
        /// Gets or Sets IdShort
        /// </summary>
        [JsonPropertyName("idShort")]
        public string? IdShort { get { return this.IdShortOption; } set { this.IdShortOption = new(value); } }

        /// <summary>
        /// Used to track the state of Extensions
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<Extension>?> ExtensionsOption { get; private set; }

        /// <summary>
        /// Gets or Sets Extensions
        /// </summary>
        [JsonPropertyName("extensions")]
        public List<Extension>? Extensions { get { return this.ExtensionsOption; } set { this.ExtensionsOption = new(value); } }

        /// <summary>
        /// Used to track the state of SemanticId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Reference?> SemanticIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets SemanticId
        /// </summary>
        [JsonPropertyName("semanticId")]
        public Reference? SemanticId { get { return this.SemanticIdOption; } set { this.SemanticIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of SupplementalSemanticIds
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<Reference>?> SupplementalSemanticIdsOption { get; private set; }

        /// <summary>
        /// Gets or Sets SupplementalSemanticIds
        /// </summary>
        [JsonPropertyName("supplementalSemanticIds")]
        public List<Reference>? SupplementalSemanticIds { get { return this.SupplementalSemanticIdsOption; } set { this.SupplementalSemanticIdsOption = new(value); } }

        /// <summary>
        /// Used to track the state of Qualifiers
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<Qualifier>?> QualifiersOption { get; private set; }

        /// <summary>
        /// Gets or Sets Qualifiers
        /// </summary>
        [JsonPropertyName("qualifiers")]
        public List<Qualifier>? Qualifiers { get { return this.QualifiersOption; } set { this.QualifiersOption = new(value); } }

        /// <summary>
        /// Used to track the state of First
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Reference?> FirstOption { get; private set; }

        /// <summary>
        /// Gets or Sets First
        /// </summary>
        [JsonPropertyName("first")]
        public Reference? First { get { return this.FirstOption; } set { this.FirstOption = new(value); } }

        /// <summary>
        /// Used to track the state of Second
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Reference?> SecondOption { get; private set; }

        /// <summary>
        /// Gets or Sets Second
        /// </summary>
        [JsonPropertyName("second")]
        public Reference? Second { get { return this.SecondOption; } set { this.SecondOption = new(value); } }

        /// <summary>
        /// Used to track the state of Annotations
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<AnnotatedRelationshipElementAllOfAnnotations>?> AnnotationsOption { get; private set; }

        /// <summary>
        /// Gets or Sets Annotations
        /// </summary>
        [JsonPropertyName("annotations")]
        public List<AnnotatedRelationshipElementAllOfAnnotations>? Annotations { get { return this.AnnotationsOption; } set { this.AnnotationsOption = new(value); } }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public Dictionary<string, JsonElement> AdditionalProperties { get; } = new Dictionary<string, JsonElement>();

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AnnotatedRelationshipElement {\n");
            sb.Append("  EmbeddedDataSpecifications: ").Append(EmbeddedDataSpecifications).Append("\n");
            sb.Append("  DisplayName: ").Append(DisplayName).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  Category: ").Append(Category).Append("\n");
            sb.Append("  IdShort: ").Append(IdShort).Append("\n");
            sb.Append("  Extensions: ").Append(Extensions).Append("\n");
            sb.Append("  SemanticId: ").Append(SemanticId).Append("\n");
            sb.Append("  SupplementalSemanticIds: ").Append(SupplementalSemanticIds).Append("\n");
            sb.Append("  Qualifiers: ").Append(Qualifiers).Append("\n");
            sb.Append("  First: ").Append(First).Append("\n");
            sb.Append("  Second: ").Append(Second).Append("\n");
            sb.Append("  Annotations: ").Append(Annotations).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="AnnotatedRelationshipElement" />
    /// </summary>
    public class AnnotatedRelationshipElementJsonConverter : JsonConverter<AnnotatedRelationshipElement>
    {
        /// <summary>
        /// Deserializes json to <see cref="AnnotatedRelationshipElement" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override AnnotatedRelationshipElement Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<List<EmbeddedDataSpecification>?> embeddedDataSpecifications = default;
            Option<List<LangStringNameType>?> displayName = default;
            Option<List<LangStringTextType>?> description = default;
            Option<string?> category = default;
            Option<string?> idShort = default;
            Option<List<Extension>?> extensions = default;
            Option<Reference?> semanticId = default;
            Option<List<Reference>?> supplementalSemanticIds = default;
            Option<List<Qualifier>?> qualifiers = default;
            Option<Reference?> first = default;
            Option<Reference?> second = default;
            Option<List<AnnotatedRelationshipElementAllOfAnnotations>?> annotations = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "embeddedDataSpecifications":
                            embeddedDataSpecifications = new Option<List<EmbeddedDataSpecification>?>(JsonSerializer.Deserialize<List<EmbeddedDataSpecification>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "displayName":
                            displayName = new Option<List<LangStringNameType>?>(JsonSerializer.Deserialize<List<LangStringNameType>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "description":
                            description = new Option<List<LangStringTextType>?>(JsonSerializer.Deserialize<List<LangStringTextType>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "category":
                            category = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "idShort":
                            idShort = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "extensions":
                            extensions = new Option<List<Extension>?>(JsonSerializer.Deserialize<List<Extension>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "semanticId":
                            semanticId = new Option<Reference?>(JsonSerializer.Deserialize<Reference>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "supplementalSemanticIds":
                            supplementalSemanticIds = new Option<List<Reference>?>(JsonSerializer.Deserialize<List<Reference>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "qualifiers":
                            qualifiers = new Option<List<Qualifier>?>(JsonSerializer.Deserialize<List<Qualifier>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "first":
                            first = new Option<Reference?>(JsonSerializer.Deserialize<Reference>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "second":
                            second = new Option<Reference?>(JsonSerializer.Deserialize<Reference>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "annotations":
                            annotations = new Option<List<AnnotatedRelationshipElementAllOfAnnotations>?>(JsonSerializer.Deserialize<List<AnnotatedRelationshipElementAllOfAnnotations>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (embeddedDataSpecifications.IsSet && embeddedDataSpecifications.Value == null)
                throw new ArgumentNullException(nameof(embeddedDataSpecifications), "Property is not nullable for class AnnotatedRelationshipElement.");

            if (displayName.IsSet && displayName.Value == null)
                throw new ArgumentNullException(nameof(displayName), "Property is not nullable for class AnnotatedRelationshipElement.");

            if (description.IsSet && description.Value == null)
                throw new ArgumentNullException(nameof(description), "Property is not nullable for class AnnotatedRelationshipElement.");

            if (category.IsSet && category.Value == null)
                throw new ArgumentNullException(nameof(category), "Property is not nullable for class AnnotatedRelationshipElement.");

            if (idShort.IsSet && idShort.Value == null)
                throw new ArgumentNullException(nameof(idShort), "Property is not nullable for class AnnotatedRelationshipElement.");

            if (extensions.IsSet && extensions.Value == null)
                throw new ArgumentNullException(nameof(extensions), "Property is not nullable for class AnnotatedRelationshipElement.");

            if (semanticId.IsSet && semanticId.Value == null)
                throw new ArgumentNullException(nameof(semanticId), "Property is not nullable for class AnnotatedRelationshipElement.");

            if (supplementalSemanticIds.IsSet && supplementalSemanticIds.Value == null)
                throw new ArgumentNullException(nameof(supplementalSemanticIds), "Property is not nullable for class AnnotatedRelationshipElement.");

            if (qualifiers.IsSet && qualifiers.Value == null)
                throw new ArgumentNullException(nameof(qualifiers), "Property is not nullable for class AnnotatedRelationshipElement.");

            if (first.IsSet && first.Value == null)
                throw new ArgumentNullException(nameof(first), "Property is not nullable for class AnnotatedRelationshipElement.");

            if (second.IsSet && second.Value == null)
                throw new ArgumentNullException(nameof(second), "Property is not nullable for class AnnotatedRelationshipElement.");

            if (annotations.IsSet && annotations.Value == null)
                throw new ArgumentNullException(nameof(annotations), "Property is not nullable for class AnnotatedRelationshipElement.");

            return new AnnotatedRelationshipElement(embeddedDataSpecifications, displayName, description, category, idShort, extensions, semanticId, supplementalSemanticIds, qualifiers, first, second, annotations);
        }

        /// <summary>
        /// Serializes a <see cref="AnnotatedRelationshipElement" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="annotatedRelationshipElement"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, AnnotatedRelationshipElement annotatedRelationshipElement, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, annotatedRelationshipElement, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="AnnotatedRelationshipElement" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="annotatedRelationshipElement"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, AnnotatedRelationshipElement annotatedRelationshipElement, JsonSerializerOptions jsonSerializerOptions)
        {
            if (annotatedRelationshipElement.EmbeddedDataSpecificationsOption.IsSet && annotatedRelationshipElement.EmbeddedDataSpecifications == null)
                throw new ArgumentNullException(nameof(annotatedRelationshipElement.EmbeddedDataSpecifications), "Property is required for class AnnotatedRelationshipElement.");

            if (annotatedRelationshipElement.DisplayNameOption.IsSet && annotatedRelationshipElement.DisplayName == null)
                throw new ArgumentNullException(nameof(annotatedRelationshipElement.DisplayName), "Property is required for class AnnotatedRelationshipElement.");

            if (annotatedRelationshipElement.DescriptionOption.IsSet && annotatedRelationshipElement.Description == null)
                throw new ArgumentNullException(nameof(annotatedRelationshipElement.Description), "Property is required for class AnnotatedRelationshipElement.");

            if (annotatedRelationshipElement.CategoryOption.IsSet && annotatedRelationshipElement.Category == null)
                throw new ArgumentNullException(nameof(annotatedRelationshipElement.Category), "Property is required for class AnnotatedRelationshipElement.");

            if (annotatedRelationshipElement.IdShortOption.IsSet && annotatedRelationshipElement.IdShort == null)
                throw new ArgumentNullException(nameof(annotatedRelationshipElement.IdShort), "Property is required for class AnnotatedRelationshipElement.");

            if (annotatedRelationshipElement.ExtensionsOption.IsSet && annotatedRelationshipElement.Extensions == null)
                throw new ArgumentNullException(nameof(annotatedRelationshipElement.Extensions), "Property is required for class AnnotatedRelationshipElement.");

            if (annotatedRelationshipElement.SemanticIdOption.IsSet && annotatedRelationshipElement.SemanticId == null)
                throw new ArgumentNullException(nameof(annotatedRelationshipElement.SemanticId), "Property is required for class AnnotatedRelationshipElement.");

            if (annotatedRelationshipElement.SupplementalSemanticIdsOption.IsSet && annotatedRelationshipElement.SupplementalSemanticIds == null)
                throw new ArgumentNullException(nameof(annotatedRelationshipElement.SupplementalSemanticIds), "Property is required for class AnnotatedRelationshipElement.");

            if (annotatedRelationshipElement.QualifiersOption.IsSet && annotatedRelationshipElement.Qualifiers == null)
                throw new ArgumentNullException(nameof(annotatedRelationshipElement.Qualifiers), "Property is required for class AnnotatedRelationshipElement.");

            if (annotatedRelationshipElement.FirstOption.IsSet && annotatedRelationshipElement.First == null)
                throw new ArgumentNullException(nameof(annotatedRelationshipElement.First), "Property is required for class AnnotatedRelationshipElement.");

            if (annotatedRelationshipElement.SecondOption.IsSet && annotatedRelationshipElement.Second == null)
                throw new ArgumentNullException(nameof(annotatedRelationshipElement.Second), "Property is required for class AnnotatedRelationshipElement.");

            if (annotatedRelationshipElement.AnnotationsOption.IsSet && annotatedRelationshipElement.Annotations == null)
                throw new ArgumentNullException(nameof(annotatedRelationshipElement.Annotations), "Property is required for class AnnotatedRelationshipElement.");

            if (annotatedRelationshipElement.EmbeddedDataSpecificationsOption.IsSet)
            {
                writer.WritePropertyName("embeddedDataSpecifications");
                JsonSerializer.Serialize(writer, annotatedRelationshipElement.EmbeddedDataSpecifications, jsonSerializerOptions);
            }
            if (annotatedRelationshipElement.DisplayNameOption.IsSet)
            {
                writer.WritePropertyName("displayName");
                JsonSerializer.Serialize(writer, annotatedRelationshipElement.DisplayName, jsonSerializerOptions);
            }
            if (annotatedRelationshipElement.DescriptionOption.IsSet)
            {
                writer.WritePropertyName("description");
                JsonSerializer.Serialize(writer, annotatedRelationshipElement.Description, jsonSerializerOptions);
            }
            if (annotatedRelationshipElement.CategoryOption.IsSet)
                writer.WriteString("category", annotatedRelationshipElement.Category);

            if (annotatedRelationshipElement.IdShortOption.IsSet)
                writer.WriteString("idShort", annotatedRelationshipElement.IdShort);

            if (annotatedRelationshipElement.ExtensionsOption.IsSet)
            {
                writer.WritePropertyName("extensions");
                JsonSerializer.Serialize(writer, annotatedRelationshipElement.Extensions, jsonSerializerOptions);
            }
            if (annotatedRelationshipElement.SemanticIdOption.IsSet)
            {
                writer.WritePropertyName("semanticId");
                JsonSerializer.Serialize(writer, annotatedRelationshipElement.SemanticId, jsonSerializerOptions);
            }
            if (annotatedRelationshipElement.SupplementalSemanticIdsOption.IsSet)
            {
                writer.WritePropertyName("supplementalSemanticIds");
                JsonSerializer.Serialize(writer, annotatedRelationshipElement.SupplementalSemanticIds, jsonSerializerOptions);
            }
            if (annotatedRelationshipElement.QualifiersOption.IsSet)
            {
                writer.WritePropertyName("qualifiers");
                JsonSerializer.Serialize(writer, annotatedRelationshipElement.Qualifiers, jsonSerializerOptions);
            }
            if (annotatedRelationshipElement.FirstOption.IsSet)
            {
                writer.WritePropertyName("first");
                JsonSerializer.Serialize(writer, annotatedRelationshipElement.First, jsonSerializerOptions);
            }
            if (annotatedRelationshipElement.SecondOption.IsSet)
            {
                writer.WritePropertyName("second");
                JsonSerializer.Serialize(writer, annotatedRelationshipElement.Second, jsonSerializerOptions);
            }
            if (annotatedRelationshipElement.AnnotationsOption.IsSet)
            {
                writer.WritePropertyName("annotations");
                JsonSerializer.Serialize(writer, annotatedRelationshipElement.Annotations, jsonSerializerOptions);
            }
        }
    }
}
