// <auto-generated>
/*
 * BaSyx AAS Environment Component
 *
 * AAS Environment API
 *
 * The version of the OpenAPI document: 2.0
 * Contact: basyx-dev@eclipse.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using MnestixSearcher.Clients.Client;

namespace MnestixSearcher.Clients.Model
{
    /// <summary>
    /// EmbeddedDataSpecificationDataSpecificationContent
    /// </summary>
    public partial class EmbeddedDataSpecificationDataSpecificationContent : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EmbeddedDataSpecificationDataSpecificationContent" /> class.
        /// </summary>
        /// <param name="object"></param>
        public EmbeddedDataSpecificationDataSpecificationContent(Object @object)
        {
            Object = @object;
            OnCreated();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="EmbeddedDataSpecificationDataSpecificationContent" /> class.
        /// </summary>
        /// <param name="dataSpecificationIec61360"></param>
        public EmbeddedDataSpecificationDataSpecificationContent(DataSpecificationIec61360 dataSpecificationIec61360)
        {
            DataSpecificationIec61360 = dataSpecificationIec61360;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Object
        /// </summary>
        public Object? Object { get; set; }

        /// <summary>
        /// Gets or Sets DataSpecificationIec61360
        /// </summary>
        public DataSpecificationIec61360? DataSpecificationIec61360 { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public Dictionary<string, JsonElement> AdditionalProperties { get; } = new Dictionary<string, JsonElement>();

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class EmbeddedDataSpecificationDataSpecificationContent {\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="EmbeddedDataSpecificationDataSpecificationContent" />
    /// </summary>
    public class EmbeddedDataSpecificationDataSpecificationContentJsonConverter : JsonConverter<EmbeddedDataSpecificationDataSpecificationContent>
    {
        /// <summary>
        /// Deserializes json to <see cref="EmbeddedDataSpecificationDataSpecificationContent" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override EmbeddedDataSpecificationDataSpecificationContent Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Object? varObject = default;
            DataSpecificationIec61360? dataSpecificationIec61360 = default;

            Utf8JsonReader utf8JsonReaderOneOf = utf8JsonReader;
            while (utf8JsonReaderOneOf.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReaderOneOf.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReaderOneOf.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReaderOneOf.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReaderOneOf.CurrentDepth)
                    break;

                if (utf8JsonReaderOneOf.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReaderOneOf.CurrentDepth - 1)
                {
                    Utf8JsonReader utf8JsonReaderObject = utf8JsonReader;
                    ClientUtils.TryDeserialize<Object?>(ref utf8JsonReaderObject, jsonSerializerOptions, out varObject);

                    Utf8JsonReader utf8JsonReaderDataSpecificationIec61360 = utf8JsonReader;
                    ClientUtils.TryDeserialize<DataSpecificationIec61360?>(ref utf8JsonReaderDataSpecificationIec61360, jsonSerializerOptions, out dataSpecificationIec61360);
                }
            }

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        default:
                            break;
                    }
                }
            }

            if (varObject != null)
                return new EmbeddedDataSpecificationDataSpecificationContent(varObject);

            if (dataSpecificationIec61360 != null)
                return new EmbeddedDataSpecificationDataSpecificationContent(dataSpecificationIec61360);

            throw new JsonException();
        }

        /// <summary>
        /// Serializes a <see cref="EmbeddedDataSpecificationDataSpecificationContent" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="embeddedDataSpecificationDataSpecificationContent"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, EmbeddedDataSpecificationDataSpecificationContent embeddedDataSpecificationDataSpecificationContent, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, embeddedDataSpecificationDataSpecificationContent, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="EmbeddedDataSpecificationDataSpecificationContent" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="embeddedDataSpecificationDataSpecificationContent"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, EmbeddedDataSpecificationDataSpecificationContent embeddedDataSpecificationDataSpecificationContent, JsonSerializerOptions jsonSerializerOptions)
        {

        }
    }
}
