// <auto-generated>
/*
 * BaSyx AAS Environment Component
 *
 * AAS Environment API
 *
 * The version of the OpenAPI document: 2.0
 * Contact: basyx-dev@eclipse.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using MnestixSearcher.Clients.Client;

namespace MnestixSearcher.Clients.Model
{
    /// <summary>
    /// Operation
    /// </summary>
    public partial class Operation : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Operation" /> class.
        /// </summary>
        /// <param name="embeddedDataSpecifications">embeddedDataSpecifications</param>
        /// <param name="displayName">displayName</param>
        /// <param name="description">description</param>
        /// <param name="category">category</param>
        /// <param name="idShort">idShort</param>
        /// <param name="extensions">extensions</param>
        /// <param name="semanticId">semanticId</param>
        /// <param name="supplementalSemanticIds">supplementalSemanticIds</param>
        /// <param name="qualifiers">qualifiers</param>
        /// <param name="inputVariables">inputVariables</param>
        /// <param name="outputVariables">outputVariables</param>
        /// <param name="inoutputVariables">inoutputVariables</param>
        [JsonConstructor]
        public Operation(Option<List<EmbeddedDataSpecification>?> embeddedDataSpecifications = default, Option<List<LangStringNameType>?> displayName = default, Option<List<LangStringTextType>?> description = default, Option<string?> category = default, Option<string?> idShort = default, Option<List<Extension>?> extensions = default, Option<Reference?> semanticId = default, Option<List<Reference>?> supplementalSemanticIds = default, Option<List<Qualifier>?> qualifiers = default, Option<List<OperationVariable>?> inputVariables = default, Option<List<OperationVariable>?> outputVariables = default, Option<List<OperationVariable>?> inoutputVariables = default)
        {
            EmbeddedDataSpecificationsOption = embeddedDataSpecifications;
            DisplayNameOption = displayName;
            DescriptionOption = description;
            CategoryOption = category;
            IdShortOption = idShort;
            ExtensionsOption = extensions;
            SemanticIdOption = semanticId;
            SupplementalSemanticIdsOption = supplementalSemanticIds;
            QualifiersOption = qualifiers;
            InputVariablesOption = inputVariables;
            OutputVariablesOption = outputVariables;
            InoutputVariablesOption = inoutputVariables;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of EmbeddedDataSpecifications
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<EmbeddedDataSpecification>?> EmbeddedDataSpecificationsOption { get; private set; }

        /// <summary>
        /// Gets or Sets EmbeddedDataSpecifications
        /// </summary>
        [JsonPropertyName("embeddedDataSpecifications")]
        public List<EmbeddedDataSpecification>? EmbeddedDataSpecifications { get { return this.EmbeddedDataSpecificationsOption; } set { this.EmbeddedDataSpecificationsOption = new(value); } }

        /// <summary>
        /// Used to track the state of DisplayName
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<LangStringNameType>?> DisplayNameOption { get; private set; }

        /// <summary>
        /// Gets or Sets DisplayName
        /// </summary>
        [JsonPropertyName("displayName")]
        public List<LangStringNameType>? DisplayName { get { return this.DisplayNameOption; } set { this.DisplayNameOption = new(value); } }

        /// <summary>
        /// Used to track the state of Description
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<LangStringTextType>?> DescriptionOption { get; private set; }

        /// <summary>
        /// Gets or Sets Description
        /// </summary>
        [JsonPropertyName("description")]
        public List<LangStringTextType>? Description { get { return this.DescriptionOption; } set { this.DescriptionOption = new(value); } }

        /// <summary>
        /// Used to track the state of Category
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> CategoryOption { get; private set; }

        /// <summary>
        /// Gets or Sets Category
        /// </summary>
        [JsonPropertyName("category")]
        public string? Category { get { return this.CategoryOption; } set { this.CategoryOption = new(value); } }

        /// <summary>
        /// Used to track the state of IdShort
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> IdShortOption { get; private set; }

        /// <summary>
        /// Gets or Sets IdShort
        /// </summary>
        [JsonPropertyName("idShort")]
        public string? IdShort { get { return this.IdShortOption; } set { this.IdShortOption = new(value); } }

        /// <summary>
        /// Used to track the state of Extensions
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<Extension>?> ExtensionsOption { get; private set; }

        /// <summary>
        /// Gets or Sets Extensions
        /// </summary>
        [JsonPropertyName("extensions")]
        public List<Extension>? Extensions { get { return this.ExtensionsOption; } set { this.ExtensionsOption = new(value); } }

        /// <summary>
        /// Used to track the state of SemanticId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Reference?> SemanticIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets SemanticId
        /// </summary>
        [JsonPropertyName("semanticId")]
        public Reference? SemanticId { get { return this.SemanticIdOption; } set { this.SemanticIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of SupplementalSemanticIds
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<Reference>?> SupplementalSemanticIdsOption { get; private set; }

        /// <summary>
        /// Gets or Sets SupplementalSemanticIds
        /// </summary>
        [JsonPropertyName("supplementalSemanticIds")]
        public List<Reference>? SupplementalSemanticIds { get { return this.SupplementalSemanticIdsOption; } set { this.SupplementalSemanticIdsOption = new(value); } }

        /// <summary>
        /// Used to track the state of Qualifiers
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<Qualifier>?> QualifiersOption { get; private set; }

        /// <summary>
        /// Gets or Sets Qualifiers
        /// </summary>
        [JsonPropertyName("qualifiers")]
        public List<Qualifier>? Qualifiers { get { return this.QualifiersOption; } set { this.QualifiersOption = new(value); } }

        /// <summary>
        /// Used to track the state of InputVariables
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<OperationVariable>?> InputVariablesOption { get; private set; }

        /// <summary>
        /// Gets or Sets InputVariables
        /// </summary>
        [JsonPropertyName("inputVariables")]
        public List<OperationVariable>? InputVariables { get { return this.InputVariablesOption; } set { this.InputVariablesOption = new(value); } }

        /// <summary>
        /// Used to track the state of OutputVariables
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<OperationVariable>?> OutputVariablesOption { get; private set; }

        /// <summary>
        /// Gets or Sets OutputVariables
        /// </summary>
        [JsonPropertyName("outputVariables")]
        public List<OperationVariable>? OutputVariables { get { return this.OutputVariablesOption; } set { this.OutputVariablesOption = new(value); } }

        /// <summary>
        /// Used to track the state of InoutputVariables
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<OperationVariable>?> InoutputVariablesOption { get; private set; }

        /// <summary>
        /// Gets or Sets InoutputVariables
        /// </summary>
        [JsonPropertyName("inoutputVariables")]
        public List<OperationVariable>? InoutputVariables { get { return this.InoutputVariablesOption; } set { this.InoutputVariablesOption = new(value); } }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public Dictionary<string, JsonElement> AdditionalProperties { get; } = new Dictionary<string, JsonElement>();

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Operation {\n");
            sb.Append("  EmbeddedDataSpecifications: ").Append(EmbeddedDataSpecifications).Append("\n");
            sb.Append("  DisplayName: ").Append(DisplayName).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  Category: ").Append(Category).Append("\n");
            sb.Append("  IdShort: ").Append(IdShort).Append("\n");
            sb.Append("  Extensions: ").Append(Extensions).Append("\n");
            sb.Append("  SemanticId: ").Append(SemanticId).Append("\n");
            sb.Append("  SupplementalSemanticIds: ").Append(SupplementalSemanticIds).Append("\n");
            sb.Append("  Qualifiers: ").Append(Qualifiers).Append("\n");
            sb.Append("  InputVariables: ").Append(InputVariables).Append("\n");
            sb.Append("  OutputVariables: ").Append(OutputVariables).Append("\n");
            sb.Append("  InoutputVariables: ").Append(InoutputVariables).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="Operation" />
    /// </summary>
    public class OperationJsonConverter : JsonConverter<Operation>
    {
        /// <summary>
        /// Deserializes json to <see cref="Operation" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override Operation Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<List<EmbeddedDataSpecification>?> embeddedDataSpecifications = default;
            Option<List<LangStringNameType>?> displayName = default;
            Option<List<LangStringTextType>?> description = default;
            Option<string?> category = default;
            Option<string?> idShort = default;
            Option<List<Extension>?> extensions = default;
            Option<Reference?> semanticId = default;
            Option<List<Reference>?> supplementalSemanticIds = default;
            Option<List<Qualifier>?> qualifiers = default;
            Option<List<OperationVariable>?> inputVariables = default;
            Option<List<OperationVariable>?> outputVariables = default;
            Option<List<OperationVariable>?> inoutputVariables = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "embeddedDataSpecifications":
                            embeddedDataSpecifications = new Option<List<EmbeddedDataSpecification>?>(JsonSerializer.Deserialize<List<EmbeddedDataSpecification>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "displayName":
                            displayName = new Option<List<LangStringNameType>?>(JsonSerializer.Deserialize<List<LangStringNameType>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "description":
                            description = new Option<List<LangStringTextType>?>(JsonSerializer.Deserialize<List<LangStringTextType>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "category":
                            category = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "idShort":
                            idShort = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "extensions":
                            extensions = new Option<List<Extension>?>(JsonSerializer.Deserialize<List<Extension>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "semanticId":
                            semanticId = new Option<Reference?>(JsonSerializer.Deserialize<Reference>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "supplementalSemanticIds":
                            supplementalSemanticIds = new Option<List<Reference>?>(JsonSerializer.Deserialize<List<Reference>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "qualifiers":
                            qualifiers = new Option<List<Qualifier>?>(JsonSerializer.Deserialize<List<Qualifier>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "inputVariables":
                            inputVariables = new Option<List<OperationVariable>?>(JsonSerializer.Deserialize<List<OperationVariable>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "outputVariables":
                            outputVariables = new Option<List<OperationVariable>?>(JsonSerializer.Deserialize<List<OperationVariable>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "inoutputVariables":
                            inoutputVariables = new Option<List<OperationVariable>?>(JsonSerializer.Deserialize<List<OperationVariable>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (embeddedDataSpecifications.IsSet && embeddedDataSpecifications.Value == null)
                throw new ArgumentNullException(nameof(embeddedDataSpecifications), "Property is not nullable for class Operation.");

            if (displayName.IsSet && displayName.Value == null)
                throw new ArgumentNullException(nameof(displayName), "Property is not nullable for class Operation.");

            if (description.IsSet && description.Value == null)
                throw new ArgumentNullException(nameof(description), "Property is not nullable for class Operation.");

            if (category.IsSet && category.Value == null)
                throw new ArgumentNullException(nameof(category), "Property is not nullable for class Operation.");

            if (idShort.IsSet && idShort.Value == null)
                throw new ArgumentNullException(nameof(idShort), "Property is not nullable for class Operation.");

            if (extensions.IsSet && extensions.Value == null)
                throw new ArgumentNullException(nameof(extensions), "Property is not nullable for class Operation.");

            if (semanticId.IsSet && semanticId.Value == null)
                throw new ArgumentNullException(nameof(semanticId), "Property is not nullable for class Operation.");

            if (supplementalSemanticIds.IsSet && supplementalSemanticIds.Value == null)
                throw new ArgumentNullException(nameof(supplementalSemanticIds), "Property is not nullable for class Operation.");

            if (qualifiers.IsSet && qualifiers.Value == null)
                throw new ArgumentNullException(nameof(qualifiers), "Property is not nullable for class Operation.");

            if (inputVariables.IsSet && inputVariables.Value == null)
                throw new ArgumentNullException(nameof(inputVariables), "Property is not nullable for class Operation.");

            if (outputVariables.IsSet && outputVariables.Value == null)
                throw new ArgumentNullException(nameof(outputVariables), "Property is not nullable for class Operation.");

            if (inoutputVariables.IsSet && inoutputVariables.Value == null)
                throw new ArgumentNullException(nameof(inoutputVariables), "Property is not nullable for class Operation.");

            return new Operation(embeddedDataSpecifications, displayName, description, category, idShort, extensions, semanticId, supplementalSemanticIds, qualifiers, inputVariables, outputVariables, inoutputVariables);
        }

        /// <summary>
        /// Serializes a <see cref="Operation" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="operation"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, Operation operation, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, operation, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="Operation" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="operation"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, Operation operation, JsonSerializerOptions jsonSerializerOptions)
        {
            if (operation.EmbeddedDataSpecificationsOption.IsSet && operation.EmbeddedDataSpecifications == null)
                throw new ArgumentNullException(nameof(operation.EmbeddedDataSpecifications), "Property is required for class Operation.");

            if (operation.DisplayNameOption.IsSet && operation.DisplayName == null)
                throw new ArgumentNullException(nameof(operation.DisplayName), "Property is required for class Operation.");

            if (operation.DescriptionOption.IsSet && operation.Description == null)
                throw new ArgumentNullException(nameof(operation.Description), "Property is required for class Operation.");

            if (operation.CategoryOption.IsSet && operation.Category == null)
                throw new ArgumentNullException(nameof(operation.Category), "Property is required for class Operation.");

            if (operation.IdShortOption.IsSet && operation.IdShort == null)
                throw new ArgumentNullException(nameof(operation.IdShort), "Property is required for class Operation.");

            if (operation.ExtensionsOption.IsSet && operation.Extensions == null)
                throw new ArgumentNullException(nameof(operation.Extensions), "Property is required for class Operation.");

            if (operation.SemanticIdOption.IsSet && operation.SemanticId == null)
                throw new ArgumentNullException(nameof(operation.SemanticId), "Property is required for class Operation.");

            if (operation.SupplementalSemanticIdsOption.IsSet && operation.SupplementalSemanticIds == null)
                throw new ArgumentNullException(nameof(operation.SupplementalSemanticIds), "Property is required for class Operation.");

            if (operation.QualifiersOption.IsSet && operation.Qualifiers == null)
                throw new ArgumentNullException(nameof(operation.Qualifiers), "Property is required for class Operation.");

            if (operation.InputVariablesOption.IsSet && operation.InputVariables == null)
                throw new ArgumentNullException(nameof(operation.InputVariables), "Property is required for class Operation.");

            if (operation.OutputVariablesOption.IsSet && operation.OutputVariables == null)
                throw new ArgumentNullException(nameof(operation.OutputVariables), "Property is required for class Operation.");

            if (operation.InoutputVariablesOption.IsSet && operation.InoutputVariables == null)
                throw new ArgumentNullException(nameof(operation.InoutputVariables), "Property is required for class Operation.");

            if (operation.EmbeddedDataSpecificationsOption.IsSet)
            {
                writer.WritePropertyName("embeddedDataSpecifications");
                JsonSerializer.Serialize(writer, operation.EmbeddedDataSpecifications, jsonSerializerOptions);
            }
            if (operation.DisplayNameOption.IsSet)
            {
                writer.WritePropertyName("displayName");
                JsonSerializer.Serialize(writer, operation.DisplayName, jsonSerializerOptions);
            }
            if (operation.DescriptionOption.IsSet)
            {
                writer.WritePropertyName("description");
                JsonSerializer.Serialize(writer, operation.Description, jsonSerializerOptions);
            }
            if (operation.CategoryOption.IsSet)
                writer.WriteString("category", operation.Category);

            if (operation.IdShortOption.IsSet)
                writer.WriteString("idShort", operation.IdShort);

            if (operation.ExtensionsOption.IsSet)
            {
                writer.WritePropertyName("extensions");
                JsonSerializer.Serialize(writer, operation.Extensions, jsonSerializerOptions);
            }
            if (operation.SemanticIdOption.IsSet)
            {
                writer.WritePropertyName("semanticId");
                JsonSerializer.Serialize(writer, operation.SemanticId, jsonSerializerOptions);
            }
            if (operation.SupplementalSemanticIdsOption.IsSet)
            {
                writer.WritePropertyName("supplementalSemanticIds");
                JsonSerializer.Serialize(writer, operation.SupplementalSemanticIds, jsonSerializerOptions);
            }
            if (operation.QualifiersOption.IsSet)
            {
                writer.WritePropertyName("qualifiers");
                JsonSerializer.Serialize(writer, operation.Qualifiers, jsonSerializerOptions);
            }
            if (operation.InputVariablesOption.IsSet)
            {
                writer.WritePropertyName("inputVariables");
                JsonSerializer.Serialize(writer, operation.InputVariables, jsonSerializerOptions);
            }
            if (operation.OutputVariablesOption.IsSet)
            {
                writer.WritePropertyName("outputVariables");
                JsonSerializer.Serialize(writer, operation.OutputVariables, jsonSerializerOptions);
            }
            if (operation.InoutputVariablesOption.IsSet)
            {
                writer.WritePropertyName("inoutputVariables");
                JsonSerializer.Serialize(writer, operation.InoutputVariables, jsonSerializerOptions);
            }
        }
    }
}
