// <auto-generated>
/*
 * BaSyx AAS Environment Component
 *
 * AAS Environment API
 *
 * The version of the OpenAPI document: 2.0
 * Contact: basyx-dev@eclipse.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using MnestixSearcher.Clients.Client;

namespace MnestixSearcher.Clients.Model
{
    /// <summary>
    /// PagedResultPagingMetadata
    /// </summary>
    public partial class PagedResultPagingMetadata : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PagedResultPagingMetadata" /> class.
        /// </summary>
        /// <param name="cursor">cursor</param>
        [JsonConstructor]
        public PagedResultPagingMetadata(Option<string?> cursor = default)
        {
            CursorOption = cursor;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Cursor
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> CursorOption { get; private set; }

        /// <summary>
        /// Gets or Sets Cursor
        /// </summary>
        /* <example>wJlCDLIl6KTWypN7T6vc6nWEmEYe99Hjf1XY1xmqV-M&#x3D;#</example> */
        [JsonPropertyName("cursor")]
        public string? Cursor { get { return this.CursorOption; } set { this.CursorOption = new(value); } }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public Dictionary<string, JsonElement> AdditionalProperties { get; } = new Dictionary<string, JsonElement>();

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PagedResultPagingMetadata {\n");
            sb.Append("  Cursor: ").Append(Cursor).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="PagedResultPagingMetadata" />
    /// </summary>
    public class PagedResultPagingMetadataJsonConverter : JsonConverter<PagedResultPagingMetadata>
    {
        /// <summary>
        /// Deserializes json to <see cref="PagedResultPagingMetadata" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override PagedResultPagingMetadata Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> cursor = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "cursor":
                            cursor = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (cursor.IsSet && cursor.Value == null)
                throw new ArgumentNullException(nameof(cursor), "Property is not nullable for class PagedResultPagingMetadata.");

            return new PagedResultPagingMetadata(cursor);
        }

        /// <summary>
        /// Serializes a <see cref="PagedResultPagingMetadata" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="pagedResultPagingMetadata"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, PagedResultPagingMetadata pagedResultPagingMetadata, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, pagedResultPagingMetadata, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="PagedResultPagingMetadata" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="pagedResultPagingMetadata"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, PagedResultPagingMetadata pagedResultPagingMetadata, JsonSerializerOptions jsonSerializerOptions)
        {
            if (pagedResultPagingMetadata.CursorOption.IsSet && pagedResultPagingMetadata.Cursor == null)
                throw new ArgumentNullException(nameof(pagedResultPagingMetadata.Cursor), "Property is required for class PagedResultPagingMetadata.");

            if (pagedResultPagingMetadata.CursorOption.IsSet)
                writer.WriteString("cursor", pagedResultPagingMetadata.Cursor);
        }
    }
}
