// <auto-generated>
/*
 * BaSyx AAS Environment Component
 *
 * AAS Environment API
 *
 * The version of the OpenAPI document: 2.0
 * Contact: basyx-dev@eclipse.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using MnestixSearcher.Clients.Client;

namespace MnestixSearcher.Clients.Model
{
    /// <summary>
    /// Qualifier
    /// </summary>
    public partial class Qualifier : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Qualifier" /> class.
        /// </summary>
        /// <param name="type">type</param>
        /// <param name="value">value</param>
        /// <param name="kind">kind</param>
        /// <param name="valueType">valueType</param>
        /// <param name="valueId">valueId</param>
        /// <param name="semanticId">semanticId</param>
        /// <param name="supplementalSemanticIds">supplementalSemanticIds</param>
        [JsonConstructor]
        public Qualifier(Option<string?> type = default, Option<string?> value = default, Option<KindEnum?> kind = default, Option<ValueTypeEnum?> valueType = default, Option<Reference?> valueId = default, Option<Reference?> semanticId = default, Option<List<Reference>?> supplementalSemanticIds = default)
        {
            TypeOption = type;
            ValueOption = value;
            KindOption = kind;
            ValueTypeOption = valueType;
            ValueIdOption = valueId;
            SemanticIdOption = semanticId;
            SupplementalSemanticIdsOption = supplementalSemanticIds;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Defines Kind
        /// </summary>
        public enum KindEnum
        {
            /// <summary>
            /// Enum CONCEPTQUALIFIER for value: CONCEPT_QUALIFIER
            /// </summary>
            CONCEPTQUALIFIER = 1,

            /// <summary>
            /// Enum TEMPLATEQUALIFIER for value: TEMPLATE_QUALIFIER
            /// </summary>
            TEMPLATEQUALIFIER = 2,

            /// <summary>
            /// Enum VALUEQUALIFIER for value: VALUE_QUALIFIER
            /// </summary>
            VALUEQUALIFIER = 3
        }

        /// <summary>
        /// Returns a <see cref="KindEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static KindEnum KindEnumFromString(string value)
        {
            if (value.Equals("CONCEPT_QUALIFIER"))
                return KindEnum.CONCEPTQUALIFIER;

            if (value.Equals("TEMPLATE_QUALIFIER"))
                return KindEnum.TEMPLATEQUALIFIER;

            if (value.Equals("VALUE_QUALIFIER"))
                return KindEnum.VALUEQUALIFIER;

            throw new NotImplementedException($"Could not convert value to type KindEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="KindEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static KindEnum? KindEnumFromStringOrDefault(string value)
        {
            if (value.Equals("CONCEPT_QUALIFIER"))
                return KindEnum.CONCEPTQUALIFIER;

            if (value.Equals("TEMPLATE_QUALIFIER"))
                return KindEnum.TEMPLATEQUALIFIER;

            if (value.Equals("VALUE_QUALIFIER"))
                return KindEnum.VALUEQUALIFIER;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="KindEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string KindEnumToJsonValue(KindEnum? value)
        {
            if (value == KindEnum.CONCEPTQUALIFIER)
                return "CONCEPT_QUALIFIER";

            if (value == KindEnum.TEMPLATEQUALIFIER)
                return "TEMPLATE_QUALIFIER";

            if (value == KindEnum.VALUEQUALIFIER)
                return "VALUE_QUALIFIER";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Used to track the state of Kind
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<KindEnum?> KindOption { get; private set; }

        /// <summary>
        /// Gets or Sets Kind
        /// </summary>
        [JsonPropertyName("kind")]
        public KindEnum? Kind { get { return this.KindOption; } set { this.KindOption = new(value); } }

        /// <summary>
        /// Defines ValueType
        /// </summary>
        public enum ValueTypeEnum
        {
            /// <summary>
            /// Enum ANYURI for value: ANY_URI
            /// </summary>
            ANYURI = 1,

            /// <summary>
            /// Enum BASE64BINARY for value: BASE64BINARY
            /// </summary>
            BASE64BINARY = 2,

            /// <summary>
            /// Enum BOOLEAN for value: BOOLEAN
            /// </summary>
            BOOLEAN = 3,

            /// <summary>
            /// Enum BYTE for value: BYTE
            /// </summary>
            BYTE = 4,

            /// <summary>
            /// Enum DATE for value: DATE
            /// </summary>
            DATE = 5,

            /// <summary>
            /// Enum DATETIME for value: DATE_TIME
            /// </summary>
            DATETIME = 6,

            /// <summary>
            /// Enum DECIMAL for value: DECIMAL
            /// </summary>
            DECIMAL = 7,

            /// <summary>
            /// Enum DOUBLE for value: DOUBLE
            /// </summary>
            DOUBLE = 8,

            /// <summary>
            /// Enum DURATION for value: DURATION
            /// </summary>
            DURATION = 9,

            /// <summary>
            /// Enum FLOAT for value: FLOAT
            /// </summary>
            FLOAT = 10,

            /// <summary>
            /// Enum GDAY for value: GDAY
            /// </summary>
            GDAY = 11,

            /// <summary>
            /// Enum GMONTH for value: GMONTH
            /// </summary>
            GMONTH = 12,

            /// <summary>
            /// Enum GMONTHDAY for value: GMONTH_DAY
            /// </summary>
            GMONTHDAY = 13,

            /// <summary>
            /// Enum GYEAR for value: GYEAR
            /// </summary>
            GYEAR = 14,

            /// <summary>
            /// Enum GYEARMONTH for value: GYEAR_MONTH
            /// </summary>
            GYEARMONTH = 15,

            /// <summary>
            /// Enum HEXBINARY for value: HEX_BINARY
            /// </summary>
            HEXBINARY = 16,

            /// <summary>
            /// Enum INT for value: INT
            /// </summary>
            INT = 17,

            /// <summary>
            /// Enum INTEGER for value: INTEGER
            /// </summary>
            INTEGER = 18,

            /// <summary>
            /// Enum LONG for value: LONG
            /// </summary>
            LONG = 19,

            /// <summary>
            /// Enum NEGATIVEINTEGER for value: NEGATIVE_INTEGER
            /// </summary>
            NEGATIVEINTEGER = 20,

            /// <summary>
            /// Enum NONNEGATIVEINTEGER for value: NON_NEGATIVE_INTEGER
            /// </summary>
            NONNEGATIVEINTEGER = 21,

            /// <summary>
            /// Enum NONPOSITIVEINTEGER for value: NON_POSITIVE_INTEGER
            /// </summary>
            NONPOSITIVEINTEGER = 22,

            /// <summary>
            /// Enum POSITIVEINTEGER for value: POSITIVE_INTEGER
            /// </summary>
            POSITIVEINTEGER = 23,

            /// <summary>
            /// Enum SHORT for value: SHORT
            /// </summary>
            SHORT = 24,

            /// <summary>
            /// Enum STRING for value: STRING
            /// </summary>
            STRING = 25,

            /// <summary>
            /// Enum TIME for value: TIME
            /// </summary>
            TIME = 26,

            /// <summary>
            /// Enum UNSIGNEDBYTE for value: UNSIGNED_BYTE
            /// </summary>
            UNSIGNEDBYTE = 27,

            /// <summary>
            /// Enum UNSIGNEDINT for value: UNSIGNED_INT
            /// </summary>
            UNSIGNEDINT = 28,

            /// <summary>
            /// Enum UNSIGNEDLONG for value: UNSIGNED_LONG
            /// </summary>
            UNSIGNEDLONG = 29,

            /// <summary>
            /// Enum UNSIGNEDSHORT for value: UNSIGNED_SHORT
            /// </summary>
            UNSIGNEDSHORT = 30
        }

        /// <summary>
        /// Returns a <see cref="ValueTypeEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static ValueTypeEnum ValueTypeEnumFromString(string value)
        {
            if (value.Equals("ANY_URI"))
                return ValueTypeEnum.ANYURI;

            if (value.Equals("BASE64BINARY"))
                return ValueTypeEnum.BASE64BINARY;

            if (value.Equals("BOOLEAN"))
                return ValueTypeEnum.BOOLEAN;

            if (value.Equals("BYTE"))
                return ValueTypeEnum.BYTE;

            if (value.Equals("DATE"))
                return ValueTypeEnum.DATE;

            if (value.Equals("DATE_TIME"))
                return ValueTypeEnum.DATETIME;

            if (value.Equals("DECIMAL"))
                return ValueTypeEnum.DECIMAL;

            if (value.Equals("DOUBLE"))
                return ValueTypeEnum.DOUBLE;

            if (value.Equals("DURATION"))
                return ValueTypeEnum.DURATION;

            if (value.Equals("FLOAT"))
                return ValueTypeEnum.FLOAT;

            if (value.Equals("GDAY"))
                return ValueTypeEnum.GDAY;

            if (value.Equals("GMONTH"))
                return ValueTypeEnum.GMONTH;

            if (value.Equals("GMONTH_DAY"))
                return ValueTypeEnum.GMONTHDAY;

            if (value.Equals("GYEAR"))
                return ValueTypeEnum.GYEAR;

            if (value.Equals("GYEAR_MONTH"))
                return ValueTypeEnum.GYEARMONTH;

            if (value.Equals("HEX_BINARY"))
                return ValueTypeEnum.HEXBINARY;

            if (value.Equals("INT"))
                return ValueTypeEnum.INT;

            if (value.Equals("INTEGER"))
                return ValueTypeEnum.INTEGER;

            if (value.Equals("LONG"))
                return ValueTypeEnum.LONG;

            if (value.Equals("NEGATIVE_INTEGER"))
                return ValueTypeEnum.NEGATIVEINTEGER;

            if (value.Equals("NON_NEGATIVE_INTEGER"))
                return ValueTypeEnum.NONNEGATIVEINTEGER;

            if (value.Equals("NON_POSITIVE_INTEGER"))
                return ValueTypeEnum.NONPOSITIVEINTEGER;

            if (value.Equals("POSITIVE_INTEGER"))
                return ValueTypeEnum.POSITIVEINTEGER;

            if (value.Equals("SHORT"))
                return ValueTypeEnum.SHORT;

            if (value.Equals("STRING"))
                return ValueTypeEnum.STRING;

            if (value.Equals("TIME"))
                return ValueTypeEnum.TIME;

            if (value.Equals("UNSIGNED_BYTE"))
                return ValueTypeEnum.UNSIGNEDBYTE;

            if (value.Equals("UNSIGNED_INT"))
                return ValueTypeEnum.UNSIGNEDINT;

            if (value.Equals("UNSIGNED_LONG"))
                return ValueTypeEnum.UNSIGNEDLONG;

            if (value.Equals("UNSIGNED_SHORT"))
                return ValueTypeEnum.UNSIGNEDSHORT;

            throw new NotImplementedException($"Could not convert value to type ValueTypeEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="ValueTypeEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static ValueTypeEnum? ValueTypeEnumFromStringOrDefault(string value)
        {
            if (value.Equals("ANY_URI"))
                return ValueTypeEnum.ANYURI;

            if (value.Equals("BASE64BINARY"))
                return ValueTypeEnum.BASE64BINARY;

            if (value.Equals("BOOLEAN"))
                return ValueTypeEnum.BOOLEAN;

            if (value.Equals("BYTE"))
                return ValueTypeEnum.BYTE;

            if (value.Equals("DATE"))
                return ValueTypeEnum.DATE;

            if (value.Equals("DATE_TIME"))
                return ValueTypeEnum.DATETIME;

            if (value.Equals("DECIMAL"))
                return ValueTypeEnum.DECIMAL;

            if (value.Equals("DOUBLE"))
                return ValueTypeEnum.DOUBLE;

            if (value.Equals("DURATION"))
                return ValueTypeEnum.DURATION;

            if (value.Equals("FLOAT"))
                return ValueTypeEnum.FLOAT;

            if (value.Equals("GDAY"))
                return ValueTypeEnum.GDAY;

            if (value.Equals("GMONTH"))
                return ValueTypeEnum.GMONTH;

            if (value.Equals("GMONTH_DAY"))
                return ValueTypeEnum.GMONTHDAY;

            if (value.Equals("GYEAR"))
                return ValueTypeEnum.GYEAR;

            if (value.Equals("GYEAR_MONTH"))
                return ValueTypeEnum.GYEARMONTH;

            if (value.Equals("HEX_BINARY"))
                return ValueTypeEnum.HEXBINARY;

            if (value.Equals("INT"))
                return ValueTypeEnum.INT;

            if (value.Equals("INTEGER"))
                return ValueTypeEnum.INTEGER;

            if (value.Equals("LONG"))
                return ValueTypeEnum.LONG;

            if (value.Equals("NEGATIVE_INTEGER"))
                return ValueTypeEnum.NEGATIVEINTEGER;

            if (value.Equals("NON_NEGATIVE_INTEGER"))
                return ValueTypeEnum.NONNEGATIVEINTEGER;

            if (value.Equals("NON_POSITIVE_INTEGER"))
                return ValueTypeEnum.NONPOSITIVEINTEGER;

            if (value.Equals("POSITIVE_INTEGER"))
                return ValueTypeEnum.POSITIVEINTEGER;

            if (value.Equals("SHORT"))
                return ValueTypeEnum.SHORT;

            if (value.Equals("STRING"))
                return ValueTypeEnum.STRING;

            if (value.Equals("TIME"))
                return ValueTypeEnum.TIME;

            if (value.Equals("UNSIGNED_BYTE"))
                return ValueTypeEnum.UNSIGNEDBYTE;

            if (value.Equals("UNSIGNED_INT"))
                return ValueTypeEnum.UNSIGNEDINT;

            if (value.Equals("UNSIGNED_LONG"))
                return ValueTypeEnum.UNSIGNEDLONG;

            if (value.Equals("UNSIGNED_SHORT"))
                return ValueTypeEnum.UNSIGNEDSHORT;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="ValueTypeEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string ValueTypeEnumToJsonValue(ValueTypeEnum? value)
        {
            if (value == ValueTypeEnum.ANYURI)
                return "ANY_URI";

            if (value == ValueTypeEnum.BASE64BINARY)
                return "BASE64BINARY";

            if (value == ValueTypeEnum.BOOLEAN)
                return "BOOLEAN";

            if (value == ValueTypeEnum.BYTE)
                return "BYTE";

            if (value == ValueTypeEnum.DATE)
                return "DATE";

            if (value == ValueTypeEnum.DATETIME)
                return "DATE_TIME";

            if (value == ValueTypeEnum.DECIMAL)
                return "DECIMAL";

            if (value == ValueTypeEnum.DOUBLE)
                return "DOUBLE";

            if (value == ValueTypeEnum.DURATION)
                return "DURATION";

            if (value == ValueTypeEnum.FLOAT)
                return "FLOAT";

            if (value == ValueTypeEnum.GDAY)
                return "GDAY";

            if (value == ValueTypeEnum.GMONTH)
                return "GMONTH";

            if (value == ValueTypeEnum.GMONTHDAY)
                return "GMONTH_DAY";

            if (value == ValueTypeEnum.GYEAR)
                return "GYEAR";

            if (value == ValueTypeEnum.GYEARMONTH)
                return "GYEAR_MONTH";

            if (value == ValueTypeEnum.HEXBINARY)
                return "HEX_BINARY";

            if (value == ValueTypeEnum.INT)
                return "INT";

            if (value == ValueTypeEnum.INTEGER)
                return "INTEGER";

            if (value == ValueTypeEnum.LONG)
                return "LONG";

            if (value == ValueTypeEnum.NEGATIVEINTEGER)
                return "NEGATIVE_INTEGER";

            if (value == ValueTypeEnum.NONNEGATIVEINTEGER)
                return "NON_NEGATIVE_INTEGER";

            if (value == ValueTypeEnum.NONPOSITIVEINTEGER)
                return "NON_POSITIVE_INTEGER";

            if (value == ValueTypeEnum.POSITIVEINTEGER)
                return "POSITIVE_INTEGER";

            if (value == ValueTypeEnum.SHORT)
                return "SHORT";

            if (value == ValueTypeEnum.STRING)
                return "STRING";

            if (value == ValueTypeEnum.TIME)
                return "TIME";

            if (value == ValueTypeEnum.UNSIGNEDBYTE)
                return "UNSIGNED_BYTE";

            if (value == ValueTypeEnum.UNSIGNEDINT)
                return "UNSIGNED_INT";

            if (value == ValueTypeEnum.UNSIGNEDLONG)
                return "UNSIGNED_LONG";

            if (value == ValueTypeEnum.UNSIGNEDSHORT)
                return "UNSIGNED_SHORT";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Used to track the state of ValueType
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<ValueTypeEnum?> ValueTypeOption { get; private set; }

        /// <summary>
        /// Gets or Sets ValueType
        /// </summary>
        [JsonPropertyName("valueType")]
        public ValueTypeEnum? ValueType { get { return this.ValueTypeOption; } set { this.ValueTypeOption = new(value); } }

        /// <summary>
        /// Used to track the state of Type
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> TypeOption { get; private set; }

        /// <summary>
        /// Gets or Sets Type
        /// </summary>
        [JsonPropertyName("type")]
        public string? Type { get { return this.TypeOption; } set { this.TypeOption = new(value); } }

        /// <summary>
        /// Used to track the state of Value
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ValueOption { get; private set; }

        /// <summary>
        /// Gets or Sets Value
        /// </summary>
        [JsonPropertyName("value")]
        public string? Value { get { return this.ValueOption; } set { this.ValueOption = new(value); } }

        /// <summary>
        /// Used to track the state of ValueId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Reference?> ValueIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets ValueId
        /// </summary>
        [JsonPropertyName("valueId")]
        public Reference? ValueId { get { return this.ValueIdOption; } set { this.ValueIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of SemanticId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Reference?> SemanticIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets SemanticId
        /// </summary>
        [JsonPropertyName("semanticId")]
        public Reference? SemanticId { get { return this.SemanticIdOption; } set { this.SemanticIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of SupplementalSemanticIds
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<Reference>?> SupplementalSemanticIdsOption { get; private set; }

        /// <summary>
        /// Gets or Sets SupplementalSemanticIds
        /// </summary>
        [JsonPropertyName("supplementalSemanticIds")]
        public List<Reference>? SupplementalSemanticIds { get { return this.SupplementalSemanticIdsOption; } set { this.SupplementalSemanticIdsOption = new(value); } }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public Dictionary<string, JsonElement> AdditionalProperties { get; } = new Dictionary<string, JsonElement>();

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Qualifier {\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  Value: ").Append(Value).Append("\n");
            sb.Append("  Kind: ").Append(Kind).Append("\n");
            sb.Append("  ValueType: ").Append(ValueType).Append("\n");
            sb.Append("  ValueId: ").Append(ValueId).Append("\n");
            sb.Append("  SemanticId: ").Append(SemanticId).Append("\n");
            sb.Append("  SupplementalSemanticIds: ").Append(SupplementalSemanticIds).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="Qualifier" />
    /// </summary>
    public class QualifierJsonConverter : JsonConverter<Qualifier>
    {
        /// <summary>
        /// Deserializes json to <see cref="Qualifier" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override Qualifier Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> type = default;
            Option<string?> value = default;
            Option<Qualifier.KindEnum?> kind = default;
            Option<Qualifier.ValueTypeEnum?> valueType = default;
            Option<Reference?> valueId = default;
            Option<Reference?> semanticId = default;
            Option<List<Reference>?> supplementalSemanticIds = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "type":
                            type = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "value":
                            value = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "kind":
                            string? kindRawValue = utf8JsonReader.GetString();
                            if (kindRawValue != null)
                                kind = new Option<Qualifier.KindEnum?>(Qualifier.KindEnumFromStringOrDefault(kindRawValue));
                            break;
                        case "valueType":
                            string? valueTypeRawValue = utf8JsonReader.GetString();
                            if (valueTypeRawValue != null)
                                valueType = new Option<Qualifier.ValueTypeEnum?>(Qualifier.ValueTypeEnumFromStringOrDefault(valueTypeRawValue));
                            break;
                        case "valueId":
                            valueId = new Option<Reference?>(JsonSerializer.Deserialize<Reference>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "semanticId":
                            semanticId = new Option<Reference?>(JsonSerializer.Deserialize<Reference>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "supplementalSemanticIds":
                            supplementalSemanticIds = new Option<List<Reference>?>(JsonSerializer.Deserialize<List<Reference>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (type.IsSet && type.Value == null)
                throw new ArgumentNullException(nameof(type), "Property is not nullable for class Qualifier.");

            if (value.IsSet && value.Value == null)
                throw new ArgumentNullException(nameof(value), "Property is not nullable for class Qualifier.");

            if (kind.IsSet && kind.Value == null)
                throw new ArgumentNullException(nameof(kind), "Property is not nullable for class Qualifier.");

            if (valueType.IsSet && valueType.Value == null)
                throw new ArgumentNullException(nameof(valueType), "Property is not nullable for class Qualifier.");

            if (valueId.IsSet && valueId.Value == null)
                throw new ArgumentNullException(nameof(valueId), "Property is not nullable for class Qualifier.");

            if (semanticId.IsSet && semanticId.Value == null)
                throw new ArgumentNullException(nameof(semanticId), "Property is not nullable for class Qualifier.");

            if (supplementalSemanticIds.IsSet && supplementalSemanticIds.Value == null)
                throw new ArgumentNullException(nameof(supplementalSemanticIds), "Property is not nullable for class Qualifier.");

            return new Qualifier(type, value, kind, valueType, valueId, semanticId, supplementalSemanticIds);
        }

        /// <summary>
        /// Serializes a <see cref="Qualifier" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="qualifier"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, Qualifier qualifier, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, qualifier, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="Qualifier" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="qualifier"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, Qualifier qualifier, JsonSerializerOptions jsonSerializerOptions)
        {
            if (qualifier.TypeOption.IsSet && qualifier.Type == null)
                throw new ArgumentNullException(nameof(qualifier.Type), "Property is required for class Qualifier.");

            if (qualifier.ValueOption.IsSet && qualifier.Value == null)
                throw new ArgumentNullException(nameof(qualifier.Value), "Property is required for class Qualifier.");

            if (qualifier.ValueIdOption.IsSet && qualifier.ValueId == null)
                throw new ArgumentNullException(nameof(qualifier.ValueId), "Property is required for class Qualifier.");

            if (qualifier.SemanticIdOption.IsSet && qualifier.SemanticId == null)
                throw new ArgumentNullException(nameof(qualifier.SemanticId), "Property is required for class Qualifier.");

            if (qualifier.SupplementalSemanticIdsOption.IsSet && qualifier.SupplementalSemanticIds == null)
                throw new ArgumentNullException(nameof(qualifier.SupplementalSemanticIds), "Property is required for class Qualifier.");

            if (qualifier.TypeOption.IsSet)
                writer.WriteString("type", qualifier.Type);

            if (qualifier.ValueOption.IsSet)
                writer.WriteString("value", qualifier.Value);

            var kindRawValue = Qualifier.KindEnumToJsonValue(qualifier.KindOption.Value!.Value);
            writer.WriteString("kind", kindRawValue);
            var valueTypeRawValue = Qualifier.ValueTypeEnumToJsonValue(qualifier.ValueTypeOption.Value!.Value);
            writer.WriteString("valueType", valueTypeRawValue);
            if (qualifier.ValueIdOption.IsSet)
            {
                writer.WritePropertyName("valueId");
                JsonSerializer.Serialize(writer, qualifier.ValueId, jsonSerializerOptions);
            }
            if (qualifier.SemanticIdOption.IsSet)
            {
                writer.WritePropertyName("semanticId");
                JsonSerializer.Serialize(writer, qualifier.SemanticId, jsonSerializerOptions);
            }
            if (qualifier.SupplementalSemanticIdsOption.IsSet)
            {
                writer.WritePropertyName("supplementalSemanticIds");
                JsonSerializer.Serialize(writer, qualifier.SupplementalSemanticIds, jsonSerializerOptions);
            }
        }
    }
}
