// <auto-generated>
/*
 * BaSyx AAS Environment Component
 *
 * AAS Environment API
 *
 * The version of the OpenAPI document: 2.0
 * Contact: basyx-dev@eclipse.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using MnestixSearcher.Clients.Client;

namespace MnestixSearcher.Clients.Model
{
    /// <summary>
    /// The Description object enables servers to present their capabilities to the clients, in particular which profiles they implement. At least one defined profile is required. Additional, proprietary attributes might be included. Nevertheless, the server must not expect that a regular client understands them.
    /// </summary>
    public partial class ServiceDescription : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ServiceDescription" /> class.
        /// </summary>
        /// <param name="profiles">profiles</param>
        [JsonConstructor]
        public ServiceDescription(Option<List<ServiceDescription.ProfilesEnum>?> profiles = default)
        {
            ProfilesOption = profiles;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Defines Profiles
        /// </summary>
        public enum ProfilesEnum
        {
            /// <summary>
            /// Enum HttpsAdminShellIoAasAPI30AssetAdministrationShellServiceSpecificationSSP001 for value: https://admin-shell.io/aas/API/3/0/AssetAdministrationShellServiceSpecification/SSP-001
            /// </summary>
            HttpsAdminShellIoAasAPI30AssetAdministrationShellServiceSpecificationSSP001 = 1,

            /// <summary>
            /// Enum HttpsAdminShellIoAasAPI30AssetAdministrationShellServiceSpecificationSSP002 for value: https://admin-shell.io/aas/API/3/0/AssetAdministrationShellServiceSpecification/SSP-002
            /// </summary>
            HttpsAdminShellIoAasAPI30AssetAdministrationShellServiceSpecificationSSP002 = 2,

            /// <summary>
            /// Enum HttpsAdminShellIoAasAPI30SubmodelServiceSpecificationSSP001 for value: https://admin-shell.io/aas/API/3/0/SubmodelServiceSpecification/SSP-001
            /// </summary>
            HttpsAdminShellIoAasAPI30SubmodelServiceSpecificationSSP001 = 3,

            /// <summary>
            /// Enum HttpsAdminShellIoAasAPI30SubmodelServiceSpecificationSSP002 for value: https://admin-shell.io/aas/API/3/0/SubmodelServiceSpecification/SSP-002
            /// </summary>
            HttpsAdminShellIoAasAPI30SubmodelServiceSpecificationSSP002 = 4,

            /// <summary>
            /// Enum HttpsAdminShellIoAasAPI30SubmodelServiceSpecificationSSP003 for value: https://admin-shell.io/aas/API/3/0/SubmodelServiceSpecification/SSP-003
            /// </summary>
            HttpsAdminShellIoAasAPI30SubmodelServiceSpecificationSSP003 = 5,

            /// <summary>
            /// Enum HttpsAdminShellIoAasAPI30AasxFileServerServiceSpecificationSSP001 for value: https://admin-shell.io/aas/API/3/0/AasxFileServerServiceSpecification/SSP-001
            /// </summary>
            HttpsAdminShellIoAasAPI30AasxFileServerServiceSpecificationSSP001 = 6,

            /// <summary>
            /// Enum HttpsAdminShellIoAasAPI30AssetAdministrationShellRegistryServiceSpecificationSSP001 for value: https://admin-shell.io/aas/API/3/0/AssetAdministrationShellRegistryServiceSpecification/SSP-001
            /// </summary>
            HttpsAdminShellIoAasAPI30AssetAdministrationShellRegistryServiceSpecificationSSP001 = 7,

            /// <summary>
            /// Enum HttpsAdminShellIoAasAPI30AssetAdministrationShellRegistryServiceSpecificationSSP002 for value: https://admin-shell.io/aas/API/3/0/AssetAdministrationShellRegistryServiceSpecification/SSP-002
            /// </summary>
            HttpsAdminShellIoAasAPI30AssetAdministrationShellRegistryServiceSpecificationSSP002 = 8,

            /// <summary>
            /// Enum HttpsAdminShellIoAasAPI30SubmodelRegistryServiceSpecificationSSP001 for value: https://admin-shell.io/aas/API/3/0/SubmodelRegistryServiceSpecification/SSP-001
            /// </summary>
            HttpsAdminShellIoAasAPI30SubmodelRegistryServiceSpecificationSSP001 = 9,

            /// <summary>
            /// Enum HttpsAdminShellIoAasAPI30SubmodelRegistryServiceSpecificationSSP002 for value: https://admin-shell.io/aas/API/3/0/SubmodelRegistryServiceSpecification/SSP-002
            /// </summary>
            HttpsAdminShellIoAasAPI30SubmodelRegistryServiceSpecificationSSP002 = 10,

            /// <summary>
            /// Enum HttpsAdminShellIoAasAPI30DiscoveryServiceSpecificationSSP001 for value: https://admin-shell.io/aas/API/3/0/DiscoveryServiceSpecification/SSP-001
            /// </summary>
            HttpsAdminShellIoAasAPI30DiscoveryServiceSpecificationSSP001 = 11,

            /// <summary>
            /// Enum HttpsAdminShellIoAasAPI30AssetAdministrationShellRepositoryServiceSpecificationSSP001 for value: https://admin-shell.io/aas/API/3/0/AssetAdministrationShellRepositoryServiceSpecification/SSP-001
            /// </summary>
            HttpsAdminShellIoAasAPI30AssetAdministrationShellRepositoryServiceSpecificationSSP001 = 12,

            /// <summary>
            /// Enum HttpsAdminShellIoAasAPI30AssetAdministrationShellRepositoryServiceSpecificationSSP002 for value: https://admin-shell.io/aas/API/3/0/AssetAdministrationShellRepositoryServiceSpecification/SSP-002
            /// </summary>
            HttpsAdminShellIoAasAPI30AssetAdministrationShellRepositoryServiceSpecificationSSP002 = 13,

            /// <summary>
            /// Enum HttpsAdminShellIoAasAPI30SubmodelRepositoryServiceSpecificationSSP001 for value: https://admin-shell.io/aas/API/3/0/SubmodelRepositoryServiceSpecification/SSP-001
            /// </summary>
            HttpsAdminShellIoAasAPI30SubmodelRepositoryServiceSpecificationSSP001 = 14,

            /// <summary>
            /// Enum HttpsAdminShellIoAasAPI30SubmodelRepositoryServiceSpecificationSSP002 for value: https://admin-shell.io/aas/API/3/0/SubmodelRepositoryServiceSpecification/SSP-002
            /// </summary>
            HttpsAdminShellIoAasAPI30SubmodelRepositoryServiceSpecificationSSP002 = 15,

            /// <summary>
            /// Enum HttpsAdminShellIoAasAPI30SubmodelRepositoryServiceSpecificationSSP003 for value: https://admin-shell.io/aas/API/3/0/SubmodelRepositoryServiceSpecification/SSP-003
            /// </summary>
            HttpsAdminShellIoAasAPI30SubmodelRepositoryServiceSpecificationSSP003 = 16,

            /// <summary>
            /// Enum HttpsAdminShellIoAasAPI30SubmodelRepositoryServiceSpecificationSSP004 for value: https://admin-shell.io/aas/API/3/0/SubmodelRepositoryServiceSpecification/SSP-004
            /// </summary>
            HttpsAdminShellIoAasAPI30SubmodelRepositoryServiceSpecificationSSP004 = 17,

            /// <summary>
            /// Enum HttpsAdminShellIoAasAPI30ConceptDescriptionServiceSpecificationSSP001 for value: https://admin-shell.io/aas/API/3/0/ConceptDescriptionServiceSpecification/SSP-001
            /// </summary>
            HttpsAdminShellIoAasAPI30ConceptDescriptionServiceSpecificationSSP001 = 18
        }

        /// <summary>
        /// Returns a <see cref="ProfilesEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static ProfilesEnum ProfilesEnumFromString(string value)
        {
            if (value.Equals("https://admin-shell.io/aas/API/3/0/AssetAdministrationShellServiceSpecification/SSP-001"))
                return ProfilesEnum.HttpsAdminShellIoAasAPI30AssetAdministrationShellServiceSpecificationSSP001;

            if (value.Equals("https://admin-shell.io/aas/API/3/0/AssetAdministrationShellServiceSpecification/SSP-002"))
                return ProfilesEnum.HttpsAdminShellIoAasAPI30AssetAdministrationShellServiceSpecificationSSP002;

            if (value.Equals("https://admin-shell.io/aas/API/3/0/SubmodelServiceSpecification/SSP-001"))
                return ProfilesEnum.HttpsAdminShellIoAasAPI30SubmodelServiceSpecificationSSP001;

            if (value.Equals("https://admin-shell.io/aas/API/3/0/SubmodelServiceSpecification/SSP-002"))
                return ProfilesEnum.HttpsAdminShellIoAasAPI30SubmodelServiceSpecificationSSP002;

            if (value.Equals("https://admin-shell.io/aas/API/3/0/SubmodelServiceSpecification/SSP-003"))
                return ProfilesEnum.HttpsAdminShellIoAasAPI30SubmodelServiceSpecificationSSP003;

            if (value.Equals("https://admin-shell.io/aas/API/3/0/AasxFileServerServiceSpecification/SSP-001"))
                return ProfilesEnum.HttpsAdminShellIoAasAPI30AasxFileServerServiceSpecificationSSP001;

            if (value.Equals("https://admin-shell.io/aas/API/3/0/AssetAdministrationShellRegistryServiceSpecification/SSP-001"))
                return ProfilesEnum.HttpsAdminShellIoAasAPI30AssetAdministrationShellRegistryServiceSpecificationSSP001;

            if (value.Equals("https://admin-shell.io/aas/API/3/0/AssetAdministrationShellRegistryServiceSpecification/SSP-002"))
                return ProfilesEnum.HttpsAdminShellIoAasAPI30AssetAdministrationShellRegistryServiceSpecificationSSP002;

            if (value.Equals("https://admin-shell.io/aas/API/3/0/SubmodelRegistryServiceSpecification/SSP-001"))
                return ProfilesEnum.HttpsAdminShellIoAasAPI30SubmodelRegistryServiceSpecificationSSP001;

            if (value.Equals("https://admin-shell.io/aas/API/3/0/SubmodelRegistryServiceSpecification/SSP-002"))
                return ProfilesEnum.HttpsAdminShellIoAasAPI30SubmodelRegistryServiceSpecificationSSP002;

            if (value.Equals("https://admin-shell.io/aas/API/3/0/DiscoveryServiceSpecification/SSP-001"))
                return ProfilesEnum.HttpsAdminShellIoAasAPI30DiscoveryServiceSpecificationSSP001;

            if (value.Equals("https://admin-shell.io/aas/API/3/0/AssetAdministrationShellRepositoryServiceSpecification/SSP-001"))
                return ProfilesEnum.HttpsAdminShellIoAasAPI30AssetAdministrationShellRepositoryServiceSpecificationSSP001;

            if (value.Equals("https://admin-shell.io/aas/API/3/0/AssetAdministrationShellRepositoryServiceSpecification/SSP-002"))
                return ProfilesEnum.HttpsAdminShellIoAasAPI30AssetAdministrationShellRepositoryServiceSpecificationSSP002;

            if (value.Equals("https://admin-shell.io/aas/API/3/0/SubmodelRepositoryServiceSpecification/SSP-001"))
                return ProfilesEnum.HttpsAdminShellIoAasAPI30SubmodelRepositoryServiceSpecificationSSP001;

            if (value.Equals("https://admin-shell.io/aas/API/3/0/SubmodelRepositoryServiceSpecification/SSP-002"))
                return ProfilesEnum.HttpsAdminShellIoAasAPI30SubmodelRepositoryServiceSpecificationSSP002;

            if (value.Equals("https://admin-shell.io/aas/API/3/0/SubmodelRepositoryServiceSpecification/SSP-003"))
                return ProfilesEnum.HttpsAdminShellIoAasAPI30SubmodelRepositoryServiceSpecificationSSP003;

            if (value.Equals("https://admin-shell.io/aas/API/3/0/SubmodelRepositoryServiceSpecification/SSP-004"))
                return ProfilesEnum.HttpsAdminShellIoAasAPI30SubmodelRepositoryServiceSpecificationSSP004;

            if (value.Equals("https://admin-shell.io/aas/API/3/0/ConceptDescriptionServiceSpecification/SSP-001"))
                return ProfilesEnum.HttpsAdminShellIoAasAPI30ConceptDescriptionServiceSpecificationSSP001;

            throw new NotImplementedException($"Could not convert value to type ProfilesEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="ProfilesEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static ProfilesEnum? ProfilesEnumFromStringOrDefault(string value)
        {
            if (value.Equals("https://admin-shell.io/aas/API/3/0/AssetAdministrationShellServiceSpecification/SSP-001"))
                return ProfilesEnum.HttpsAdminShellIoAasAPI30AssetAdministrationShellServiceSpecificationSSP001;

            if (value.Equals("https://admin-shell.io/aas/API/3/0/AssetAdministrationShellServiceSpecification/SSP-002"))
                return ProfilesEnum.HttpsAdminShellIoAasAPI30AssetAdministrationShellServiceSpecificationSSP002;

            if (value.Equals("https://admin-shell.io/aas/API/3/0/SubmodelServiceSpecification/SSP-001"))
                return ProfilesEnum.HttpsAdminShellIoAasAPI30SubmodelServiceSpecificationSSP001;

            if (value.Equals("https://admin-shell.io/aas/API/3/0/SubmodelServiceSpecification/SSP-002"))
                return ProfilesEnum.HttpsAdminShellIoAasAPI30SubmodelServiceSpecificationSSP002;

            if (value.Equals("https://admin-shell.io/aas/API/3/0/SubmodelServiceSpecification/SSP-003"))
                return ProfilesEnum.HttpsAdminShellIoAasAPI30SubmodelServiceSpecificationSSP003;

            if (value.Equals("https://admin-shell.io/aas/API/3/0/AasxFileServerServiceSpecification/SSP-001"))
                return ProfilesEnum.HttpsAdminShellIoAasAPI30AasxFileServerServiceSpecificationSSP001;

            if (value.Equals("https://admin-shell.io/aas/API/3/0/AssetAdministrationShellRegistryServiceSpecification/SSP-001"))
                return ProfilesEnum.HttpsAdminShellIoAasAPI30AssetAdministrationShellRegistryServiceSpecificationSSP001;

            if (value.Equals("https://admin-shell.io/aas/API/3/0/AssetAdministrationShellRegistryServiceSpecification/SSP-002"))
                return ProfilesEnum.HttpsAdminShellIoAasAPI30AssetAdministrationShellRegistryServiceSpecificationSSP002;

            if (value.Equals("https://admin-shell.io/aas/API/3/0/SubmodelRegistryServiceSpecification/SSP-001"))
                return ProfilesEnum.HttpsAdminShellIoAasAPI30SubmodelRegistryServiceSpecificationSSP001;

            if (value.Equals("https://admin-shell.io/aas/API/3/0/SubmodelRegistryServiceSpecification/SSP-002"))
                return ProfilesEnum.HttpsAdminShellIoAasAPI30SubmodelRegistryServiceSpecificationSSP002;

            if (value.Equals("https://admin-shell.io/aas/API/3/0/DiscoveryServiceSpecification/SSP-001"))
                return ProfilesEnum.HttpsAdminShellIoAasAPI30DiscoveryServiceSpecificationSSP001;

            if (value.Equals("https://admin-shell.io/aas/API/3/0/AssetAdministrationShellRepositoryServiceSpecification/SSP-001"))
                return ProfilesEnum.HttpsAdminShellIoAasAPI30AssetAdministrationShellRepositoryServiceSpecificationSSP001;

            if (value.Equals("https://admin-shell.io/aas/API/3/0/AssetAdministrationShellRepositoryServiceSpecification/SSP-002"))
                return ProfilesEnum.HttpsAdminShellIoAasAPI30AssetAdministrationShellRepositoryServiceSpecificationSSP002;

            if (value.Equals("https://admin-shell.io/aas/API/3/0/SubmodelRepositoryServiceSpecification/SSP-001"))
                return ProfilesEnum.HttpsAdminShellIoAasAPI30SubmodelRepositoryServiceSpecificationSSP001;

            if (value.Equals("https://admin-shell.io/aas/API/3/0/SubmodelRepositoryServiceSpecification/SSP-002"))
                return ProfilesEnum.HttpsAdminShellIoAasAPI30SubmodelRepositoryServiceSpecificationSSP002;

            if (value.Equals("https://admin-shell.io/aas/API/3/0/SubmodelRepositoryServiceSpecification/SSP-003"))
                return ProfilesEnum.HttpsAdminShellIoAasAPI30SubmodelRepositoryServiceSpecificationSSP003;

            if (value.Equals("https://admin-shell.io/aas/API/3/0/SubmodelRepositoryServiceSpecification/SSP-004"))
                return ProfilesEnum.HttpsAdminShellIoAasAPI30SubmodelRepositoryServiceSpecificationSSP004;

            if (value.Equals("https://admin-shell.io/aas/API/3/0/ConceptDescriptionServiceSpecification/SSP-001"))
                return ProfilesEnum.HttpsAdminShellIoAasAPI30ConceptDescriptionServiceSpecificationSSP001;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="ProfilesEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string ProfilesEnumToJsonValue(ProfilesEnum? value)
        {
            if (value == ProfilesEnum.HttpsAdminShellIoAasAPI30AssetAdministrationShellServiceSpecificationSSP001)
                return "https://admin-shell.io/aas/API/3/0/AssetAdministrationShellServiceSpecification/SSP-001";

            if (value == ProfilesEnum.HttpsAdminShellIoAasAPI30AssetAdministrationShellServiceSpecificationSSP002)
                return "https://admin-shell.io/aas/API/3/0/AssetAdministrationShellServiceSpecification/SSP-002";

            if (value == ProfilesEnum.HttpsAdminShellIoAasAPI30SubmodelServiceSpecificationSSP001)
                return "https://admin-shell.io/aas/API/3/0/SubmodelServiceSpecification/SSP-001";

            if (value == ProfilesEnum.HttpsAdminShellIoAasAPI30SubmodelServiceSpecificationSSP002)
                return "https://admin-shell.io/aas/API/3/0/SubmodelServiceSpecification/SSP-002";

            if (value == ProfilesEnum.HttpsAdminShellIoAasAPI30SubmodelServiceSpecificationSSP003)
                return "https://admin-shell.io/aas/API/3/0/SubmodelServiceSpecification/SSP-003";

            if (value == ProfilesEnum.HttpsAdminShellIoAasAPI30AasxFileServerServiceSpecificationSSP001)
                return "https://admin-shell.io/aas/API/3/0/AasxFileServerServiceSpecification/SSP-001";

            if (value == ProfilesEnum.HttpsAdminShellIoAasAPI30AssetAdministrationShellRegistryServiceSpecificationSSP001)
                return "https://admin-shell.io/aas/API/3/0/AssetAdministrationShellRegistryServiceSpecification/SSP-001";

            if (value == ProfilesEnum.HttpsAdminShellIoAasAPI30AssetAdministrationShellRegistryServiceSpecificationSSP002)
                return "https://admin-shell.io/aas/API/3/0/AssetAdministrationShellRegistryServiceSpecification/SSP-002";

            if (value == ProfilesEnum.HttpsAdminShellIoAasAPI30SubmodelRegistryServiceSpecificationSSP001)
                return "https://admin-shell.io/aas/API/3/0/SubmodelRegistryServiceSpecification/SSP-001";

            if (value == ProfilesEnum.HttpsAdminShellIoAasAPI30SubmodelRegistryServiceSpecificationSSP002)
                return "https://admin-shell.io/aas/API/3/0/SubmodelRegistryServiceSpecification/SSP-002";

            if (value == ProfilesEnum.HttpsAdminShellIoAasAPI30DiscoveryServiceSpecificationSSP001)
                return "https://admin-shell.io/aas/API/3/0/DiscoveryServiceSpecification/SSP-001";

            if (value == ProfilesEnum.HttpsAdminShellIoAasAPI30AssetAdministrationShellRepositoryServiceSpecificationSSP001)
                return "https://admin-shell.io/aas/API/3/0/AssetAdministrationShellRepositoryServiceSpecification/SSP-001";

            if (value == ProfilesEnum.HttpsAdminShellIoAasAPI30AssetAdministrationShellRepositoryServiceSpecificationSSP002)
                return "https://admin-shell.io/aas/API/3/0/AssetAdministrationShellRepositoryServiceSpecification/SSP-002";

            if (value == ProfilesEnum.HttpsAdminShellIoAasAPI30SubmodelRepositoryServiceSpecificationSSP001)
                return "https://admin-shell.io/aas/API/3/0/SubmodelRepositoryServiceSpecification/SSP-001";

            if (value == ProfilesEnum.HttpsAdminShellIoAasAPI30SubmodelRepositoryServiceSpecificationSSP002)
                return "https://admin-shell.io/aas/API/3/0/SubmodelRepositoryServiceSpecification/SSP-002";

            if (value == ProfilesEnum.HttpsAdminShellIoAasAPI30SubmodelRepositoryServiceSpecificationSSP003)
                return "https://admin-shell.io/aas/API/3/0/SubmodelRepositoryServiceSpecification/SSP-003";

            if (value == ProfilesEnum.HttpsAdminShellIoAasAPI30SubmodelRepositoryServiceSpecificationSSP004)
                return "https://admin-shell.io/aas/API/3/0/SubmodelRepositoryServiceSpecification/SSP-004";

            if (value == ProfilesEnum.HttpsAdminShellIoAasAPI30ConceptDescriptionServiceSpecificationSSP001)
                return "https://admin-shell.io/aas/API/3/0/ConceptDescriptionServiceSpecification/SSP-001";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Used to track the state of Profiles
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<ServiceDescription.ProfilesEnum>?> ProfilesOption { get; private set; }

        /// <summary>
        /// Gets or Sets Profiles
        /// </summary>
        [JsonPropertyName("profiles")]
        public List<ServiceDescription.ProfilesEnum>? Profiles { get { return this.ProfilesOption; } set { this.ProfilesOption = new(value); } }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public Dictionary<string, JsonElement> AdditionalProperties { get; } = new Dictionary<string, JsonElement>();

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ServiceDescription {\n");
            sb.Append("  Profiles: ").Append(Profiles).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="ServiceDescription" />
    /// </summary>
    public class ServiceDescriptionJsonConverter : JsonConverter<ServiceDescription>
    {
        /// <summary>
        /// Deserializes json to <see cref="ServiceDescription" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override ServiceDescription Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<List<ServiceDescription.ProfilesEnum>?> profiles = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "profiles":
                            profiles = new Option<List<ServiceDescription.ProfilesEnum>?>(JsonSerializer.Deserialize<List<ServiceDescription.ProfilesEnum>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (profiles.IsSet && profiles.Value == null)
                throw new ArgumentNullException(nameof(profiles), "Property is not nullable for class ServiceDescription.");

            return new ServiceDescription(profiles);
        }

        /// <summary>
        /// Serializes a <see cref="ServiceDescription" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="serviceDescription"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, ServiceDescription serviceDescription, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, serviceDescription, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="ServiceDescription" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="serviceDescription"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, ServiceDescription serviceDescription, JsonSerializerOptions jsonSerializerOptions)
        {
            if (serviceDescription.ProfilesOption.IsSet && serviceDescription.Profiles == null)
                throw new ArgumentNullException(nameof(serviceDescription.Profiles), "Property is required for class ServiceDescription.");

            if (serviceDescription.ProfilesOption.IsSet)
            {
                writer.WritePropertyName("profiles");
                JsonSerializer.Serialize(writer, serviceDescription.Profiles, jsonSerializerOptions);
            }
        }
    }
}
