// <auto-generated>
/*
 * BaSyx AAS Environment Component
 *
 * AAS Environment API
 *
 * The version of the OpenAPI document: 2.0
 * Contact: basyx-dev@eclipse.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using MnestixSearcher.Clients.Client;

namespace MnestixSearcher.Clients.Model
{
    /// <summary>
    /// UploadEnvironmentRequest
    /// </summary>
    public partial class UploadEnvironmentRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UploadEnvironmentRequest" /> class.
        /// </summary>
        /// <param name="file">An environment file (XML, JSON, AASX)</param>
        [JsonConstructor]
        public UploadEnvironmentRequest(System.IO.Stream file)
        {
            File = file;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// An environment file (XML, JSON, AASX)
        /// </summary>
        /// <value>An environment file (XML, JSON, AASX)</value>
        [JsonPropertyName("file")]
        public System.IO.Stream File { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public Dictionary<string, JsonElement> AdditionalProperties { get; } = new Dictionary<string, JsonElement>();

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class UploadEnvironmentRequest {\n");
            sb.Append("  File: ").Append(File).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="UploadEnvironmentRequest" />
    /// </summary>
    public class UploadEnvironmentRequestJsonConverter : JsonConverter<UploadEnvironmentRequest>
    {
        /// <summary>
        /// Deserializes json to <see cref="UploadEnvironmentRequest" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override UploadEnvironmentRequest Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<System.IO.Stream?> file = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "file":
                            file = new Option<System.IO.Stream?>(JsonSerializer.Deserialize<System.IO.Stream>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!file.IsSet)
                throw new ArgumentException("Property is required for class UploadEnvironmentRequest.", nameof(file));

            if (file.IsSet && file.Value == null)
                throw new ArgumentNullException(nameof(file), "Property is not nullable for class UploadEnvironmentRequest.");

            return new UploadEnvironmentRequest(file.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="UploadEnvironmentRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="uploadEnvironmentRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, UploadEnvironmentRequest uploadEnvironmentRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, uploadEnvironmentRequest, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="UploadEnvironmentRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="uploadEnvironmentRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, UploadEnvironmentRequest uploadEnvironmentRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            if (uploadEnvironmentRequest.File == null)
                throw new ArgumentNullException(nameof(uploadEnvironmentRequest.File), "Property is required for class UploadEnvironmentRequest.");

            writer.WritePropertyName("file");
            JsonSerializer.Serialize(writer, uploadEnvironmentRequest.File, jsonSerializerOptions);
        }
    }
}
