// <auto-generated>
/*
 * BaSyx AAS Environment Component
 *
 * AAS Environment API
 *
 * The version of the OpenAPI document: 2.0
 * Contact: basyx-dev@eclipse.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using MnestixSearcher.Clients.Client;

namespace MnestixSearcher.Clients.Model
{
    /// <summary>
    /// ValueReferencePair
    /// </summary>
    public partial class ValueReferencePair : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ValueReferencePair" /> class.
        /// </summary>
        /// <param name="value">value</param>
        /// <param name="valueId">valueId</param>
        [JsonConstructor]
        public ValueReferencePair(Option<string?> value = default, Option<Reference?> valueId = default)
        {
            ValueOption = value;
            ValueIdOption = valueId;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Value
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ValueOption { get; private set; }

        /// <summary>
        /// Gets or Sets Value
        /// </summary>
        [JsonPropertyName("value")]
        public string? Value { get { return this.ValueOption; } set { this.ValueOption = new(value); } }

        /// <summary>
        /// Used to track the state of ValueId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Reference?> ValueIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets ValueId
        /// </summary>
        [JsonPropertyName("valueId")]
        public Reference? ValueId { get { return this.ValueIdOption; } set { this.ValueIdOption = new(value); } }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public Dictionary<string, JsonElement> AdditionalProperties { get; } = new Dictionary<string, JsonElement>();

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ValueReferencePair {\n");
            sb.Append("  Value: ").Append(Value).Append("\n");
            sb.Append("  ValueId: ").Append(ValueId).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="ValueReferencePair" />
    /// </summary>
    public class ValueReferencePairJsonConverter : JsonConverter<ValueReferencePair>
    {
        /// <summary>
        /// Deserializes json to <see cref="ValueReferencePair" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override ValueReferencePair Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> value = default;
            Option<Reference?> valueId = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "value":
                            value = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "valueId":
                            valueId = new Option<Reference?>(JsonSerializer.Deserialize<Reference>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (value.IsSet && value.Value == null)
                throw new ArgumentNullException(nameof(value), "Property is not nullable for class ValueReferencePair.");

            if (valueId.IsSet && valueId.Value == null)
                throw new ArgumentNullException(nameof(valueId), "Property is not nullable for class ValueReferencePair.");

            return new ValueReferencePair(value, valueId);
        }

        /// <summary>
        /// Serializes a <see cref="ValueReferencePair" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="valueReferencePair"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, ValueReferencePair valueReferencePair, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, valueReferencePair, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="ValueReferencePair" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="valueReferencePair"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, ValueReferencePair valueReferencePair, JsonSerializerOptions jsonSerializerOptions)
        {
            if (valueReferencePair.ValueOption.IsSet && valueReferencePair.Value == null)
                throw new ArgumentNullException(nameof(valueReferencePair.Value), "Property is required for class ValueReferencePair.");

            if (valueReferencePair.ValueIdOption.IsSet && valueReferencePair.ValueId == null)
                throw new ArgumentNullException(nameof(valueReferencePair.ValueId), "Property is required for class ValueReferencePair.");

            if (valueReferencePair.ValueOption.IsSet)
                writer.WriteString("value", valueReferencePair.Value);

            if (valueReferencePair.ValueIdOption.IsSet)
            {
                writer.WritePropertyName("valueId");
                JsonSerializer.Serialize(writer, valueReferencePair.ValueId, jsonSerializerOptions);
            }
        }
    }
}
